export const SET_FIRST = 'setFirst'
export const SET_SECOND = 'setSecond'
export const SET_THIRD = 'setThird'
export const SET_FOURTH = 'setForth'
export const SEt_ENTER_GAME = 'setEnterGame'
export const POST_GRADE = 'postGrade'
export const CHECK_MYGRADE = 'checkMyGrade'
export const SET_CURRENT_PASS = 'setCurrentPass'